# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(553, 407)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.product = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.product.setObjectName("product")
        self.gridLayout.addWidget(self.product, 0, 1, 1, 1)
        self.delete_2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.delete_2.setFont(font)
        self.delete_2.setStyleSheet("background-color: rgb(26, 211, 255)\n"
"")
        self.delete_2.setObjectName("delete_2")
        self.gridLayout.addWidget(self.delete_2, 2, 1, 1, 2)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.quintity = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.quintity.setObjectName("quintity")
        self.gridLayout.addWidget(self.quintity, 0, 3, 1, 1)
        self.shoplist = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.shoplist.setObjectName("shoplist")
        self.gridLayout.addWidget(self.shoplist, 3, 0, 1, 4)
        self.add = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.add.setFont(font)
        self.add.setStyleSheet("background-color: rgb(26, 211, 255)\n"
"")
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 1, 1, 1, 2)
        self.alert = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.alert.setText("")
        self.alert.setObjectName("alert")
        self.gridLayout.addWidget(self.alert, 5, 0, 1, 4)
        self.save = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 4, 1, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.delete_2.setText(_translate("Dialog", "Usuń"))
        self.label.setText(_translate("Dialog", "Nazwa produktu:"))
        self.label_2.setText(_translate("Dialog", "IIlość:"))
        self.add.setText(_translate("Dialog", "Dodaj"))
        self.save.setText(_translate("Dialog", "Zapisz"))
